FROM alpine:3.18.3
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG SAMBA_VERSION=4.18.5-r0

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    SAMBA_VERSION="${SAMBA_VERSION}"

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    apk add --no-cache --virtual=run-deps \
      acl \
      bash \
      ca-certificates \
      samba=${SAMBA_VERSION} \
      shadow \
      su-exec \
      tzdata \
    && \
    mkdir -p /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/* 

### Volume
VOLUME ["/etc", \
        "/var/cache/samba", \
        "/var/lib/samba", \
        "/var/log/samba",\
        "/run/samba"]

### Expose ports
EXPOSE 137/udp 138/udp 139 445

### Running User: not used, managed by docker-entrypoint.sh
#USER samba

### Start SAMBA
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["samba"]
